/*
 * Author: Nikolay Dvurechensky
 * Site: https://dvurechensky.pro/
 * Gmail: dvurechenskysoft@gmail.com
 * Last Updated: 04 мая 2026 06:52:49
 * Version: 1.0.7
 */

using System.Collections.Generic;
using System.Text;

namespace Lizerium.Localization.Generator;

public sealed partial class LocalizationGenerator
{
    private static class CodeBuilder
    {
        /// <summary>
        /// Builds the generated C# source for all localization API entries.
        /// </summary>
        /// <param name="entries">API entries derived from RESX keys.</param>
        /// <returns>Generated C# source text.</returns>
        public static string Build(IEnumerable<ApiEntry> entries)
        {
            var root = Node.Create("Localization");
            foreach (var entry in entries)
                root.Add(entry);

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("namespace Generated.Localization");
            builder.AppendLine("{");
            root.Write(builder, 1, isRoot: true);
            builder.AppendLine("}");
            return builder.ToString();
        }
    }
}
